name: coffe
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  animate_do: ^3.0.2
  another_transformer_page_view: ^1.1.0
  card_swiper: ^2.0.3
  cupertino_icons: ^1.0.2
  flashy_tab_bar2: ^0.0.4
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  lottie: ^1.3.0
  page_transition: ^2.0.5
  smooth_page_indicator: ^1.0.0+2

  

dev_dependencies:

  
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  
  assets:
    - images/
  
